name: maptask
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_map: any
  latlong2: any
  image_picker: any
  google_maps_flutter: any
  geolocator: any
  
  # SƏRT KİLİDLƏNMİŞ STABİL VERSİYALAR (Qarşısında ^ işarəsi yoxdur!):
  firebase_core: 2.32.0
  firebase_auth: 4.19.6
  cloud_firestore: 4.17.4
  firebase_storage: 11.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true